version: "3.8"

services:
  validator:
    image: test
    container_name: "${MYNODE}"
    volumes:
      - ./${MYNODE}:/app/${MYNODE}
      - ./${MYNODE}/.env:/app/${MYNODE}/.env
    env_file:
      - ./${MYNODE}/.env
    command: mrmintchain start-node --mynode ${MYNODE}
    ports:
      - "${P2P_PORT}:${P2P_PORT}"
      - "${RPC_PORT}:${RPC_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
      - "${JSON_RPC_PORT}:${JSON_RPC_PORT}"


validator2:
    image: test
    container_name: "${MYNODE}"
    volumes:
      - ./${MYNODE}:/app/${MYNODE}
      - ./${MYNODE}/.env:/app/${MYNODE}/.env
    env_file:
      - ./${MYNODE}/.env
    command: mrmintchain start-node --mynode ${MYNODE}
    ports:
      - "${P2P_PORT}:${P2P_PORT}"
      - "${RPC_PORT}:${RPC_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${GRPC_WEB_PORT}:${GRPC_WEB_PORT}"
      - "${JSON_RPC_PORT}:${JSON_RPC_PORT}"















# version: "3.9"

# services:
#   validator-setup:
#     build: .
#     image: test
#     stdin_open: true
#     tty: true
#     environment:
#       - MYNODE=my-validator-node
#     command: [ "./entrypoint.sh" ]
#     # volumes:
#     #   - ./data:/app/data
#     restart: "no"  # one-time job

#   validator-start:
#     build: .
#     image: test
#     stdin_open: true
#     tty: true
#     environment:
#       - MYNODE=my-validator-node
#     command: ["./startnode.sh"] 
#     ports:
#       - "26656:26656"  # p2p
#       - "26657:26657"  # rpc
#       - "8545:8545"    # json-rpc
#     # volumes:
#     #   - ./data:/app/data
#     # restart: unless-stopped

